package voxgig.bluefinshieldconexsdk.core

import java.util.{Map => JMap}

import voxgig.bluefinshieldconexsdk.utility.Json

// Static SDK configuration and by-name feature construction.
object Config {

  def makeConfig(): JMap[String, Object] =
    Json.parse(configJson()).asInstanceOf[JMap[String, Object]]

  // SHARED CONFIG (sdkgen rung L2).
  //
  // The SDK reads the config on every request and never writes to it, so one
  // instance is shared by every client rather than rebuilt per client - the
  // difference between parsing the embedded JSON once and once per client.
  //
  // A lazy val is initialised once, on first use, under a lock, so
  // concurrent first calls build it exactly once.
  //
  // The returned map is SHARED: treat it as read-only. Callers that need to
  // mutate should use makeConfig, which always parses a fresh copy.
  private lazy val sharedConfigVal: JMap[String, Object] = makeConfig()

  def sharedConfig(): JMap[String, Object] = sharedConfigVal

  def makeFeature(name: String): Feature = name match {
    case "audit" => new voxgig.bluefinshieldconexsdk.feature.AuditFeature()
    case "clienttrack" => new voxgig.bluefinshieldconexsdk.feature.ClienttrackFeature()
    case "idempotency" => new voxgig.bluefinshieldconexsdk.feature.IdempotencyFeature()
    case "log" => new voxgig.bluefinshieldconexsdk.feature.LogFeature()
    case "metrics" => new voxgig.bluefinshieldconexsdk.feature.MetricsFeature()
    case "paging" => new voxgig.bluefinshieldconexsdk.feature.PagingFeature()
    case "ratelimit" => new voxgig.bluefinshieldconexsdk.feature.RatelimitFeature()
    case "retry" => new voxgig.bluefinshieldconexsdk.feature.RetryFeature()
    case "telemetry" => new voxgig.bluefinshieldconexsdk.feature.TelemetryFeature()
    case "test" => new voxgig.bluefinshieldconexsdk.feature.TestFeature()
    case "timeout" => new voxgig.bluefinshieldconexsdk.feature.TimeoutFeature()
    case _ => new voxgig.bluefinshieldconexsdk.feature.BaseFeature()
  }

  private def configJson(): String = {
    val b = new StringBuilder()
    b.append("{")
    b.append(" \"main\": {")
    b.append("  \"name\": \"BluefinShieldconex\"")
    b.append(" },")
    b.append(" \"feature\": {")
    b.append("  \"audit\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"actor\": \"anonymous\",")
    b.append("    \"max\": 1000")
    b.append("   }")
    b.append("  },")
    b.append("  \"clienttrack\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"clientVersion\": \"0.0.1\"")
    b.append("   }")
    b.append("  },")
    b.append("  \"idempotency\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"header\": \"Idempotency-Key\",")
    b.append("    \"methods\": [")
    b.append("     \"POST\",")
    b.append("     \"PUT\",")
    b.append("     \"PATCH\",")
    b.append("     \"DELETE\"")
    b.append("    ],")
    b.append("    \"ops\": [")
    b.append("     \"create\",")
    b.append("     \"update\",")
    b.append("     \"remove\"")
    b.append("    ]")
    b.append("   }")
    b.append("  },")
    b.append("  \"log\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": true")
    b.append("   }")
    b.append("  },")
    b.append("  \"metrics\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   }")
    b.append("  },")
    b.append("  \"paging\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"afterVar\": \"after\",")
    b.append("    \"cursorParam\": \"cursor\",")
    b.append("    \"firstVar\": \"first\",")
    b.append("    \"limitParam\": \"limit\",")
    b.append("    \"pageParam\": \"page\",")
    b.append("    \"startPage\": 1")
    b.append("   }")
    b.append("  },")
    b.append("  \"ratelimit\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"burst\": 5,")
    b.append("    \"rate\": 5")
    b.append("   }")
    b.append("  },")
    b.append("  \"retry\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"factor\": 2,")
    b.append("    \"maxDelay\": 2000,")
    b.append("    \"minDelay\": 50,")
    b.append("    \"retries\": 2,")
    b.append("    \"statuses\": [")
    b.append("     408,")
    b.append("     425,")
    b.append("     429,")
    b.append("     500,")
    b.append("     502,")
    b.append("     503,")
    b.append("     504")
    b.append("    ]")
    b.append("   }")
    b.append("  },")
    b.append("  \"telemetry\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   }")
    b.append("  },")
    b.append("  \"test\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   }")
    b.append("  },")
    b.append("  \"timeout\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"ms\": 30000")
    b.append("   }")
    b.append("  }")
    b.append(" },")
    b.append(" \"options\": {")
    b.append("  \"base\": \"https://secure-cert.shieldconex.com/api\",")
    b.append("  \"auth\": {")
    b.append("   \"prefix\": \"Basic\"")
    b.append("  },")
    b.append("  \"headers\": {")
    b.append("   \"content-type\": \"application/json\"")
    b.append("  },")
    b.append("  \"entity\": {")
    b.append("   \"detokenize\": {},")
    b.append("   \"tokenize\": {},")
    b.append("   \"tokenize_batch\": {},")
    b.append("   \"tokenize_read\": {},")
    b.append("   \"validate\": {}")
    b.append("  }")
    b.append(" },")
    b.append(" \"entity\": {")
    b.append("  \"detokenize\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"batches\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`$ARRAY`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"type\": \"`$ARRAY`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"bfid\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"short\": \"The BFID, or Bluefin ID, is the value that is created when a tokenization request is made (i.e., it is the value retrieved from an iFrame transaction, or a /tokenization/tokenize request).\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"messageId\",")
    b.append("     \"short\": \"Message Id\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"name\",")
    b.append("     \"short\": \"Field Name.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"reference\",")
    b.append("     \"short\": \"Request Reference.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"value\",")
    b.append("     \"short\": \"Field Value.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"values\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`$ARRAY`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"type\": \"`$ARRAY`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"detokenize\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/tokenization/batch/detokenize\",")
    b.append("       \"parts\": [")
    b.append("        \"tokenization\",")
    b.append("        \"batch\",")
    b.append("        \"detokenize\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/tokenization/detokenize\",")
    b.append("       \"parts\": [")
    b.append("        \"tokenization\",")
    b.append("        \"detokenize\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"list\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"list\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"query\": [")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"bfid\",")
    b.append("          \"orig\": \"bfid\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"field_name\",")
    b.append("          \"orig\": \"field_name\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"field_value\",")
    b.append("          \"orig\": \"field_value\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"reference\",")
    b.append("          \"orig\": \"reference\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/healthcheck/detokenize\",")
    b.append("       \"parts\": [")
    b.append("        \"healthcheck\",")
    b.append("        \"detokenize\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"bfid\",")
    b.append("         \"field_name\",")
    b.append("         \"field_value\",")
    b.append("         \"reference\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body.values`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"tokenize\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"batches\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`$ARRAY`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"type\": \"`$ARRAY`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"bfid\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"short\": \"The BFID, or Bluefin ID, is the value that is created when a tokenization request is made (i.e., it is the value retrieved from an iFrame transaction, or a /tokenization/tokenize request).\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"messageId\",")
    b.append("     \"short\": \"Message Id\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"name\",")
    b.append("     \"short\": \"Field Name.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"reference\",")
    b.append("     \"short\": \"Request Reference.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"templateRef\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Template Reference\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"value\",")
    b.append("     \"short\": \"Field Value.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"values\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`$ARRAY`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"type\": \"`$ARRAY`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"tokenize\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"query\": [")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"omit\",")
    b.append("          \"orig\": \"omit\",")
    b.append("          \"type\": \"`$NUMBER`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/tokenization/batch/tokenize\",")
    b.append("       \"parts\": [")
    b.append("        \"tokenization\",")
    b.append("        \"batch\",")
    b.append("        \"tokenize\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"omit\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"query\": [")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"omit\",")
    b.append("          \"orig\": \"omit\",")
    b.append("          \"type\": \"`$NUMBER`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/tokenization/tokenize\",")
    b.append("       \"parts\": [")
    b.append("        \"tokenization\",")
    b.append("        \"tokenize\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"omit\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/tokenization/delete\",")
    b.append("       \"parts\": [")
    b.append("        \"tokenization\",")
    b.append("        \"delete\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"list\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"list\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"query\": [")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"field_name\",")
    b.append("          \"orig\": \"field_name\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"field_value\",")
    b.append("          \"orig\": \"field_value\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"reference\",")
    b.append("          \"orig\": \"reference\",")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"template_ref\",")
    b.append("          \"orig\": \"template_ref\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/healthcheck/tokenize\",")
    b.append("       \"parts\": [")
    b.append("        \"healthcheck\",")
    b.append("        \"tokenize\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"field_name\",")
    b.append("         \"field_value\",")
    b.append("         \"reference\",")
    b.append("         \"template_ref\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body.values`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"tokenize_batch\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"batches\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`$ARRAY`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"type\": \"`$ARRAY`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"messageId\",")
    b.append("     \"short\": \"Message Id\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"reference\",")
    b.append("     \"short\": \"Request Reference.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"tokenize_batch\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/tokenization/batch/delete\",")
    b.append("       \"parts\": [")
    b.append("        \"tokenization\",")
    b.append("        \"batch\",")
    b.append("        \"delete\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/tokenization/batch/read\",")
    b.append("       \"parts\": [")
    b.append("        \"tokenization\",")
    b.append("        \"batch\",")
    b.append("        \"read\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"tokenize_read\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"bfid\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"short\": \"The BFID, or Bluefin ID, is the value that is created when a tokenization request is made (i.e., it is the value retrieved from an iFrame transaction, or a /tokenization/tokenize request).\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"messageId\",")
    b.append("     \"short\": \"Message Id\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"reference\",")
    b.append("     \"short\": \"Request Reference.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"state\",")
    b.append("     \"short\": \"Tokenized State Data (if available)\",")
    b.append("     \"type\": \"`$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"values\",")
    b.append("     \"type\": \"`$ARRAY`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"tokenize_read\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/tokenization/read\",")
    b.append("       \"parts\": [")
    b.append("        \"tokenization\",")
    b.append("        \"read\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"validate\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"messageId\",")
    b.append("     \"short\": \"Message Id\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"reference\",")
    b.append("     \"short\": \"Request Reference.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"templateRef\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Template Reference.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"validate\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/partner/validate\",")
    b.append("       \"parts\": [")
    b.append("        \"partner\",")
    b.append("        \"validate\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/template/validate\",")
    b.append("       \"parts\": [")
    b.append("        \"template\",")
    b.append("        \"validate\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  }")
    b.append(" }")
    b.append("}")
    b.toString
  }
}
