// Generated API configuration (mirrors Config_java / core/config.go).

#ifndef SDK_CORE_CONFIG_HPP
#define SDK_CORE_CONFIG_HPP

#include <memory>
#include <string>

#include "../core/struct.hpp"
#include "../core/types.hpp"
#include "../feature/base.hpp"
#include "../feature/test.hpp"

namespace sdk {

inline const char* config_json() {
  return
    "{\"main\":{\"name\":\"BluefinShieldconex\"},\"feature\":{\"test\":{\"options\":{\"active\":false}}},\"options\":{\"base\":\"https://secure-cert.shieldconex.com/api\",\"auth\":{\"prefix\":\"Basic\"},\"headers\":{\"content-type\":\"application/json\"},\"entity\":{\"detokenize\":{},\"tokenize\":{},\"tokenize_batch\":{},\"tokenize_read\":{},\"validate\":{}}},\"entity\":{\"detokenize\":{\"fields\":[{\"name\":\"batches\",\"op\":{\"create\":{\"req\":true,\"type\":\"`$ARRAY`\"}},\"type\":\"`$ARRAY`\"},{\"name\":\"bfid\",\"op\":{\"create\":{\"req\":true,\"type\":\"`$STRING`\"}},\"type\":\"`$STRING`\"},{\"name\":\"messageId\",\"type\":\"`$STRING`\"},{\"name\":\"name\",\"type\":\"`$STRING`\"},{\"name\":\"reference\",\"type\":\"`$STRING`\"},{\"name\":\"value\",\"type\":\"`$STRING`\"},{\"name\":\"values\",\"op\":{\"create\":{\"req\":true,\"type\":\"`$ARRAY`\"}},\"type\":\"`$ARRAY`\"}],\"name\":\"detokenize\",\"op\":{\"create\":{\"input\":\"data\",\"name\":\"create\",\"points\":[{\"args\":{},\"kind\":\"http\",\"method\":\"POST\",\"orig\":\"/tokenization/batch/detokenize\",\"parts\":[\"tokenization\",\"batch\",\"detokenize\"],\"select\":{},\"transform\":{\"req\":\"`reqdata`\",\"res\":\"`body`\"}},{\"args\":{},\"kind\":\"http\",\"method\":\"POST\",\"orig\":\"/tokenization/detokenize\",\"parts\":[\"tokenization\",\"detokenize\"],\"select\":{},\"transform\":{\"req\":\"`reqdata`\",\"res\":\"`body`\"}}]},\"list\":{\"input\":\"data\",\"name\":\"list\",\"points\":[{\"args\":{\"query\":[{\"kind\":\"query\",\"name\":\"bfid\",\"orig\":\"bfid\",\"reqd\":true,\"type\":\"`$STRING`\"},{\"kind\":\"query\",\"name\":\"field_name\",\"orig\":\"field_name\",\"type\":\"`$STRING`\"},{\"kind\":\"query\",\"name\":\"field_value\",\"orig\":\"field_value\",\"type\":\"`$STRING`\"},{\"kind\":\"query\",\"name\":\"reference\",\"orig\":\"reference\",\"type\":\"`$STRING`\"}]},\"kind\":\"http\",\"method\":\"GET\",\"orig\":\"/healthcheck/detokenize\",\"parts\":[\"healthcheck\",\"detokenize\"],\"select\":{\"exist\":"
    "[\"bfid\",\"field_name\",\"field_value\",\"reference\"]},\"transform\":{\"req\":\"`reqdata`\",\"res\":\"`body`\"}}]}},\"relations\":{\"ancestors\":[]}},\"tokenize\":{\"fields\":[{\"name\":\"batches\",\"op\":{\"create\":{\"req\":true,\"type\":\"`$ARRAY`\"}},\"type\":\"`$ARRAY`\"},{\"name\":\"bfid\",\"op\":{\"create\":{\"req\":true,\"type\":\"`$STRING`\"}},\"type\":\"`$STRING`\"},{\"name\":\"messageId\",\"type\":\"`$STRING`\"},{\"name\":\"name\",\"type\":\"`$STRING`\"},{\"name\":\"reference\",\"type\":\"`$STRING`\"},{\"name\":\"templateRef\",\"req\":true,\"type\":\"`$STRING`\"},{\"name\":\"value\",\"type\":\"`$STRING`\"},{\"name\":\"values\",\"op\":{\"create\":{\"req\":true,\"type\":\"`$ARRAY`\"}},\"type\":\"`$ARRAY`\"}],\"name\":\"tokenize\",\"op\":{\"create\":{\"input\":\"data\",\"name\":\"create\",\"points\":[{\"args\":{\"query\":[{\"kind\":\"query\",\"name\":\"omit\",\"orig\":\"omit\",\"type\":\"`$NUMBER`\"}]},\"kind\":\"http\",\"method\":\"POST\",\"orig\":\"/tokenization/batch/tokenize\",\"parts\":[\"tokenization\",\"batch\",\"tokenize\"],\"select\":{\"exist\":[\"omit\"]},\"transform\":{\"req\":\"`reqdata`\",\"res\":\"`body`\"}},{\"args\":{\"query\":[{\"kind\":\"query\",\"name\":\"omit\",\"orig\":\"omit\",\"type\":\"`$NUMBER`\"}]},\"kind\":\"http\",\"method\":\"POST\",\"orig\":\"/tokenization/tokenize\",\"parts\":[\"tokenization\",\"tokenize\"],\"select\":{\"exist\":[\"omit\"]},\"transform\":{\"req\":\"`reqdata`\",\"res\":\"`body`\"}},{\"args\":{},\"kind\":\"http\",\"method\":\"POST\",\"orig\":\"/tokenization/delete\",\"parts\":[\"tokenization\",\"delete\"],\"select\":{},\"transform\":{\"req\":\"`reqdata`\",\"res\":\"`body`\"}}]},\"list\":{\"input\":\"data\",\"name\":\"list\",\"points\":[{\"args\":{\"query\":[{\"kind\":\"query\",\"name\":\"field_name\",\"orig\":\"field_name\",\"type\":\"`$STRING`\"},{\"kind\":\"query\",\"name\":\"field_value\",\"orig\":\"field_value\",\"type\":\"`$STRING`\"},{\"kind\":\"query\",\"name\":\"reference\",\"orig\":\"reference\",\"type"
    "\":\"`$STRING`\"},{\"kind\":\"query\",\"name\":\"template_ref\",\"orig\":\"template_ref\",\"reqd\":true,\"type\":\"`$STRING`\"}]},\"kind\":\"http\",\"method\":\"GET\",\"orig\":\"/healthcheck/tokenize\",\"parts\":[\"healthcheck\",\"tokenize\"],\"select\":{\"exist\":[\"field_name\",\"field_value\",\"reference\",\"template_ref\"]},\"transform\":{\"req\":\"`reqdata`\",\"res\":\"`body`\"}}]}},\"relations\":{\"ancestors\":[]}},\"tokenize_batch\":{\"fields\":[{\"name\":\"batches\",\"op\":{\"create\":{\"req\":true,\"type\":\"`$ARRAY`\"}},\"type\":\"`$ARRAY`\"},{\"name\":\"messageId\",\"type\":\"`$STRING`\"},{\"name\":\"reference\",\"type\":\"`$STRING`\"}],\"name\":\"tokenize_batch\",\"op\":{\"create\":{\"input\":\"data\",\"name\":\"create\",\"points\":[{\"args\":{},\"kind\":\"http\",\"method\":\"POST\",\"orig\":\"/tokenization/batch/delete\",\"parts\":[\"tokenization\",\"batch\",\"delete\"],\"select\":{},\"transform\":{\"req\":\"`reqdata`\",\"res\":\"`body`\"}},{\"args\":{},\"kind\":\"http\",\"method\":\"POST\",\"orig\":\"/tokenization/batch/read\",\"parts\":[\"tokenization\",\"batch\",\"read\"],\"select\":{},\"transform\":{\"req\":\"`reqdata`\",\"res\":\"`body`\"}}]}},\"relations\":{\"ancestors\":[]}},\"tokenize_read\":{\"fields\":[{\"name\":\"bfid\",\"op\":{\"create\":{\"req\":true,\"type\":\"`$STRING`\"}},\"type\":\"`$STRING`\"},{\"name\":\"messageId\",\"type\":\"`$STRING`\"},{\"name\":\"reference\",\"type\":\"`$STRING`\"},{\"name\":\"state\",\"type\":\"`$OBJECT`\"},{\"name\":\"values\",\"type\":\"`$ARRAY`\"}],\"name\":\"tokenize_read\",\"op\":{\"create\":{\"input\":\"data\",\"name\":\"create\",\"points\":[{\"args\":{},\"kind\":\"http\",\"method\":\"POST\",\"orig\":\"/tokenization/read\",\"parts\":[\"tokenization\",\"read\"],\"select\":{},\"transform\":{\"req\":\"`reqdata`\",\"res\":\"`body`\"}}]}},\"relations\":{\"ancestors\":[]}},\"validate\":{\"fields\":[{\"name\":\"messageId\",\"type\":\"`$STRING`\"},{\"name\":\"reference\",\"type\":\"`$STRING`\"},{\"name\":\"templat"
    "eRef\",\"req\":true,\"type\":\"`$STRING`\"}],\"name\":\"validate\",\"op\":{\"create\":{\"input\":\"data\",\"name\":\"create\",\"points\":[{\"args\":{},\"kind\":\"http\",\"method\":\"POST\",\"orig\":\"/partner/validate\",\"parts\":[\"partner\",\"validate\"],\"select\":{},\"transform\":{\"req\":\"`reqdata`\",\"res\":\"`body`\"}},{\"args\":{},\"kind\":\"http\",\"method\":\"POST\",\"orig\":\"/template/validate\",\"parts\":[\"template\",\"validate\"],\"select\":{},\"transform\":{\"req\":\"`reqdata`\",\"res\":\"`body`\"}}]}},\"relations\":{\"ancestors\":[]}}}}";
}

inline Value makeConfig() { return vs::parse_json(config_json()); }

inline FeaturePtr makeFeature(const std::string& name) {
  if (name == "test") return std::make_shared<TestFeature>();
  return std::make_shared<BaseFeature>();
}

} // namespace sdk

#endif // SDK_CORE_CONFIG_HPP
