-- BluefinShieldconex SDK public client (generated by @voxgig/sdkgen).
--
-- Constructors (newSdk / testSdk) and one op namespace per entity. Entities are
-- generic: every op delegates to the config-driven SdkRuntime, so the pipeline
-- is identical for every entity and every API.

import VoxgigStruct
import SdkRuntime
import SdkConfig

open VoxgigStruct

namespace Sdk

/-- Construct a live client from an options map (empty map = defaults). -/
def newSdk (options : Value) : SIO Value :=
  SdkRuntime.mkClientV options SdkConfig.configJson

/-- No-argument convenience constructor. -/
def newSdk0 : SIO Value := do newSdk (← emptyMap)

/-- Construct a test-mode client: operations are answered from an in-memory
    store seeded with the entity test data, so no server is needed. -/
def testSdk (seed : Value) (options : Value) : SIO Value :=
  SdkRuntime.mkTestClientV options SdkConfig.configJson seed

/-- Test client with default options. -/
def testSdk0 (seed : Value) : SIO Value := do testSdk seed (← emptyMap)

end Sdk

namespace Detokenize
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "detokenize" d co
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "detokenize" m co
end Detokenize

namespace Tokenize
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "tokenize" d co
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "tokenize" m co
end Tokenize

namespace Tokenize_batch
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "tokenize_batch" d co
end Tokenize_batch

namespace Tokenize_read
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "tokenize_read" d co
end Tokenize_read

namespace Validate
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "validate" d co
end Validate

