// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(1,
      "name", v_str("BluefinShieldconex")),
    "feature", cmap(1,
      "test", cmap(1,
        "options", cmap(1,
          "active", v_bool(false)))),
    "options", cmap(4,
      "base", v_str("https://secure-cert.shieldconex.com/api"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(5,
        "detokenize", v_map(),
        "tokenize", v_map(),
        "tokenize_batch", v_map(),
        "tokenize_read", v_map(),
        "validate", v_map()),
      "auth", cmap(1,
        "prefix", v_str("Basic"))),
    "entity", cmap(5,
      "detokenize", cmap(4,
        "fields", clist(7,
          cmap(6,
            "active", v_bool(true),
            "name", v_str("batches"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$ARRAY`"))),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(0)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("bfid"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("messageId"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("name"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("reference"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("value"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(5)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("values"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$ARRAY`"))),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(6))),
        "name", v_str("detokenize"),
        "op", cmap(2,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(2,
              cmap(9,
                "active", v_bool(true),
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/tokenization/batch/detokenize"),
                "parts", clist(3,
                  v_str("tokenization"),
                  v_str("batch"),
                  v_str("detokenize")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0)),
              cmap(9,
                "active", v_bool(true),
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/tokenization/detokenize"),
                "parts", clist(2,
                  v_str("tokenization"),
                  v_str("detokenize")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(1)))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "query", clist(4,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("bfid"),
                      "orig", v_str("bfid"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("field_name"),
                      "orig", v_str("field_name"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("field_value"),
                      "orig", v_str("field_value"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("reference"),
                      "orig", v_str("reference"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/healthcheck/detokenize"),
                "parts", clist(2,
                  v_str("healthcheck"),
                  v_str("detokenize")),
                "select", cmap(1,
                  "exist", clist(4,
                    v_str("bfid"),
                    v_str("field_name"),
                    v_str("field_value"),
                    v_str("reference"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "tokenize", cmap(4,
        "fields", clist(8,
          cmap(6,
            "active", v_bool(true),
            "name", v_str("batches"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$ARRAY`"))),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(0)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("bfid"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("messageId"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("name"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("reference"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("templateRef"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("value"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(6)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("values"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$ARRAY`"))),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(7))),
        "name", v_str("tokenize"),
        "op", cmap(2,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(3,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "query", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("omit"),
                      "orig", v_str("omit"),
                      "reqd", v_bool(false),
                      "type", v_str("`$NUMBER`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/tokenization/batch/tokenize"),
                "parts", clist(3,
                  v_str("tokenization"),
                  v_str("batch"),
                  v_str("tokenize")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("omit"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "query", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("omit"),
                      "orig", v_str("omit"),
                      "reqd", v_bool(false),
                      "type", v_str("`$NUMBER`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/tokenization/tokenize"),
                "parts", clist(2,
                  v_str("tokenization"),
                  v_str("tokenize")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("omit"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(8,
                "active", v_bool(true),
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/tokenization/delete"),
                "parts", clist(2,
                  v_str("tokenization"),
                  v_str("delete")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "query", clist(4,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("field_name"),
                      "orig", v_str("field_name"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("field_value"),
                      "orig", v_str("field_value"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("reference"),
                      "orig", v_str("reference"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("template_ref"),
                      "orig", v_str("template_ref"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/healthcheck/tokenize"),
                "parts", clist(2,
                  v_str("healthcheck"),
                  v_str("tokenize")),
                "select", cmap(1,
                  "exist", clist(4,
                    v_str("field_name"),
                    v_str("field_value"),
                    v_str("reference"),
                    v_str("template_ref"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "tokenize_batch", cmap(4,
        "fields", clist(3,
          cmap(6,
            "active", v_bool(true),
            "name", v_str("batches"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$ARRAY`"))),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("messageId"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("reference"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2))),
        "name", v_str("tokenize_batch"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(2,
              cmap(9,
                "active", v_bool(true),
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/tokenization/batch/delete"),
                "parts", clist(3,
                  v_str("tokenization"),
                  v_str("batch"),
                  v_str("delete")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0)),
              cmap(9,
                "active", v_bool(true),
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/tokenization/batch/read"),
                "parts", clist(3,
                  v_str("tokenization"),
                  v_str("batch"),
                  v_str("read")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(1))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "tokenize_read", cmap(4,
        "fields", clist(5,
          cmap(6,
            "active", v_bool(true),
            "name", v_str("bfid"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("messageId"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("reference"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("state"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("values"),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(4))),
        "name", v_str("tokenize_read"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/tokenization/read"),
                "parts", clist(2,
                  v_str("tokenization"),
                  v_str("read")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "validate", cmap(4,
        "fields", clist(3,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("messageId"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("reference"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("templateRef"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(2))),
        "name", v_str("validate"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(2,
              cmap(9,
                "active", v_bool(true),
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/partner/validate"),
                "parts", clist(2,
                  v_str("partner"),
                  v_str("validate")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0)),
              cmap(9,
                "active", v_bool(true),
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/template/validate"),
                "parts", clist(2,
                  v_str("template"),
                  v_str("validate")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(1))))),
        "relations", cmap(1,
          "ancestors", v_list()))));
}

Feature* make_feature(const char* name) {
  if (strcmp(name, "test") == 0) return feature_test_new();
  return feature_base_new();
}
