// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(4,
      "name", v_str("BluefinShieldconex"),
      "slug", v_str("bluefin-shieldconex"),
      "version", v_str("0.1.1"),
      "target", v_str("c")),
    "feature", cmap(1,
      "test", cmap(2,
        "options", cmap(1,
          "active", v_bool(false)),
        "transport", v_str("base"))),
    "options", cmap(4,
      "base", v_str("https://secure-cert.shieldconex.com/api"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(5,
        "detokenize", v_map(),
        "tokenize", v_map(),
        "tokenize_batch", v_map(),
        "tokenize_read", v_map(),
        "validate", v_map()),
      "auth", cmap(1,
        "prefix", v_str("Basic"))),
    "entity", cmap(5,
      "detokenize", cmap(4,
        "fields", clist(7,
          cmap(3,
            "name", v_str("batches"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$ARRAY`"))),
            "type", v_str("`$ARRAY`")),
          cmap(4,
            "name", v_str("bfid"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "short", v_str("The BFID, or Bluefin ID, is the value that is created when a tokenization request is made (i.e., it is the value retrieved from an iFrame transaction, or a /tokenization/tokenize request)."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("messageId"),
            "short", v_str("Message Id"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("name"),
            "short", v_str("Field Name."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("reference"),
            "short", v_str("Request Reference."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("value"),
            "short", v_str("Field Value."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("values"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$ARRAY`"))),
            "type", v_str("`$ARRAY`"))),
        "name", v_str("detokenize"),
        "op", cmap(2,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(2,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/tokenization/batch/detokenize"),
                "parts", clist(3,
                  v_str("tokenization"),
                  v_str("batch"),
                  v_str("detokenize")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/tokenization/detokenize"),
                "parts", clist(2,
                  v_str("tokenization"),
                  v_str("detokenize")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "query", clist(4,
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("bfid"),
                      "orig", v_str("bfid"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("field_name"),
                      "orig", v_str("field_name"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("field_value"),
                      "orig", v_str("field_value"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("reference"),
                      "orig", v_str("reference"),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/healthcheck/detokenize"),
                "parts", clist(2,
                  v_str("healthcheck"),
                  v_str("detokenize")),
                "select", cmap(1,
                  "exist", clist(4,
                    v_str("bfid"),
                    v_str("field_name"),
                    v_str("field_value"),
                    v_str("reference"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.values`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "tokenize", cmap(4,
        "fields", clist(8,
          cmap(3,
            "name", v_str("batches"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$ARRAY`"))),
            "type", v_str("`$ARRAY`")),
          cmap(4,
            "name", v_str("bfid"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "short", v_str("The BFID, or Bluefin ID, is the value that is created when a tokenization request is made (i.e., it is the value retrieved from an iFrame transaction, or a /tokenization/tokenize request)."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("messageId"),
            "short", v_str("Message Id"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("name"),
            "short", v_str("Field Name."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("reference"),
            "short", v_str("Request Reference."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("templateRef"),
            "req", v_bool(true),
            "short", v_str("Template Reference"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("value"),
            "short", v_str("Field Value."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("values"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$ARRAY`"))),
            "type", v_str("`$ARRAY`"))),
        "name", v_str("tokenize"),
        "op", cmap(2,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(3,
              cmap(7,
                "args", cmap(1,
                  "query", clist(1,
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("omit"),
                      "orig", v_str("omit"),
                      "type", v_str("`$NUMBER`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/tokenization/batch/tokenize"),
                "parts", clist(3,
                  v_str("tokenization"),
                  v_str("batch"),
                  v_str("tokenize")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("omit"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "query", clist(1,
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("omit"),
                      "orig", v_str("omit"),
                      "type", v_str("`$NUMBER`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/tokenization/tokenize"),
                "parts", clist(2,
                  v_str("tokenization"),
                  v_str("tokenize")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("omit"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/tokenization/delete"),
                "parts", clist(2,
                  v_str("tokenization"),
                  v_str("delete")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "query", clist(4,
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("field_name"),
                      "orig", v_str("field_name"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("field_value"),
                      "orig", v_str("field_value"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("reference"),
                      "orig", v_str("reference"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("template_ref"),
                      "orig", v_str("template_ref"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/healthcheck/tokenize"),
                "parts", clist(2,
                  v_str("healthcheck"),
                  v_str("tokenize")),
                "select", cmap(1,
                  "exist", clist(4,
                    v_str("field_name"),
                    v_str("field_value"),
                    v_str("reference"),
                    v_str("template_ref"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.values`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "tokenize_batch", cmap(4,
        "fields", clist(3,
          cmap(3,
            "name", v_str("batches"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$ARRAY`"))),
            "type", v_str("`$ARRAY`")),
          cmap(3,
            "name", v_str("messageId"),
            "short", v_str("Message Id"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("reference"),
            "short", v_str("Request Reference."),
            "type", v_str("`$STRING`"))),
        "name", v_str("tokenize_batch"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(2,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/tokenization/batch/delete"),
                "parts", clist(3,
                  v_str("tokenization"),
                  v_str("batch"),
                  v_str("delete")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/tokenization/batch/read"),
                "parts", clist(3,
                  v_str("tokenization"),
                  v_str("batch"),
                  v_str("read")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "tokenize_read", cmap(4,
        "fields", clist(5,
          cmap(4,
            "name", v_str("bfid"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "short", v_str("The BFID, or Bluefin ID, is the value that is created when a tokenization request is made (i.e., it is the value retrieved from an iFrame transaction, or a /tokenization/tokenize request)."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("messageId"),
            "short", v_str("Message Id"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("reference"),
            "short", v_str("Request Reference."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("state"),
            "short", v_str("Tokenized State Data (if available)"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("values"),
            "type", v_str("`$ARRAY`"))),
        "name", v_str("tokenize_read"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/tokenization/read"),
                "parts", clist(2,
                  v_str("tokenization"),
                  v_str("read")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "validate", cmap(4,
        "fields", clist(3,
          cmap(3,
            "name", v_str("messageId"),
            "short", v_str("Message Id"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("reference"),
            "short", v_str("Request Reference."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("templateRef"),
            "req", v_bool(true),
            "short", v_str("Template Reference."),
            "type", v_str("`$STRING`"))),
        "name", v_str("validate"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(2,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/partner/validate"),
                "parts", clist(2,
                  v_str("partner"),
                  v_str("validate")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/template/validate"),
                "parts", clist(2,
                  v_str("template"),
                  v_str("validate")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list()))));
}

// SHARED CONFIG (sdkgen rung L2).
//
// The SDK reads the config on every request and never writes to it, so one
// instance is shared by every client rather than rebuilt per client. Above the
// size threshold make_config re-parses the whole embedded JSON, so this is the
// difference between parsing the model once and once per client.
//
// Deliberately never freed: it lives for the life of the process, like any
// other program-lifetime singleton.
static voxgig_value* shared_config_val = NULL;

// The process-wide config, built once on first use.
//
// The returned value is SHARED: treat it as read-only. Callers that need to
// mutate should use make_config, which always returns a fresh copy.
voxgig_value* shared_config(void) {
  if (NULL == shared_config_val) {
    shared_config_val = make_config();
  }
  return shared_config_val;
}

Feature* feature_test_new(void);

Feature* make_feature(const char* name) {
  if (strcmp(name, "test") == 0) return feature_test_new();
  return feature_base_new();
}
