package voxgig.bluefinshieldconexsdk.core

import voxgig.bluefinshieldconexsdk.utility.Json

/** Static SDK configuration and by-name feature construction. */
@Suppress("UNCHECKED_CAST")
object Config {

  fun makeConfig(): MutableMap<String, Any?> {
    return Json.parse(configJson()) as MutableMap<String, Any?>
  }

  fun makeFeature(name: String): Feature {
    return when (name) {
      "test" -> voxgig.bluefinshieldconexsdk.feature.TestFeature()
      else -> voxgig.bluefinshieldconexsdk.feature.BaseFeature()
    }
  }

  private fun configJson(): String {
    val b = StringBuilder()
    b.append("{")
    b.append(" \"main\": {")
    b.append("  \"name\": \"BluefinShieldconex\"")
    b.append(" },")
    b.append(" \"feature\": {")
    b.append("  \"test\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   }")
    b.append("  }")
    b.append(" },")
    b.append(" \"options\": {")
    b.append("  \"base\": \"https://secure-cert.shieldconex.com/api\",")
    b.append("  \"auth\": {")
    b.append("   \"prefix\": \"Basic\"")
    b.append("  },")
    b.append("  \"headers\": {")
    b.append("   \"content-type\": \"application/json\"")
    b.append("  },")
    b.append("  \"entity\": {")
    b.append("   \"detokenize\": {},")
    b.append("   \"tokenize\": {},")
    b.append("   \"tokenize_batch\": {},")
    b.append("   \"tokenize_read\": {},")
    b.append("   \"validate\": {}")
    b.append("  }")
    b.append(" },")
    b.append(" \"entity\": {")
    b.append("  \"detokenize\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"batch\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`\$ARRAY`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$ARRAY`\",")
    b.append("     \"index\$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"bfid\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`\$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"message_id\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"name\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 3")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"reference\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 4")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"value\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`\$ARRAY`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$ARRAY`\",")
    b.append("     \"index\$\": 5")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"detokenize\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/tokenization/batch/detokenize\",")
    b.append("       \"parts\": [")
    b.append("        \"tokenization\",")
    b.append("        \"batch\",")
    b.append("        \"detokenize\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index\$\": 0")
    b.append("      },")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/tokenization/detokenize\",")
    b.append("       \"parts\": [")
    b.append("        \"tokenization\",")
    b.append("        \"detokenize\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index\$\": 1")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key\$\": \"create\"")
    b.append("    },")
    b.append("    \"list\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"list\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"query\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"bfid\",")
    b.append("          \"orig\": \"bfid\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"field_name\",")
    b.append("          \"orig\": \"field_name\",")
    b.append("          \"reqd\": false,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"field_value\",")
    b.append("          \"orig\": \"field_value\",")
    b.append("          \"reqd\": false,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"reference\",")
    b.append("          \"orig\": \"reference\",")
    b.append("          \"reqd\": false,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/healthcheck/detokenize\",")
    b.append("       \"parts\": [")
    b.append("        \"healthcheck\",")
    b.append("        \"detokenize\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"bfid\",")
    b.append("         \"field_name\",")
    b.append("         \"field_value\",")
    b.append("         \"reference\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index\$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key\$\": \"list\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"tokenize\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"batch\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`\$ARRAY`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$ARRAY`\",")
    b.append("     \"index\$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"bfid\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`\$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"message_id\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"name\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 3")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"reference\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 4")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"template_ref\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 5")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"value\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`\$ARRAY`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$ARRAY`\",")
    b.append("     \"index\$\": 6")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"tokenize\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"query\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"omit\",")
    b.append("          \"orig\": \"omit\",")
    b.append("          \"reqd\": false,")
    b.append("          \"type\": \"`\$NUMBER`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/tokenization/batch/tokenize\",")
    b.append("       \"parts\": [")
    b.append("        \"tokenization\",")
    b.append("        \"batch\",")
    b.append("        \"tokenize\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"omit\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index\$\": 0")
    b.append("      },")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"query\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"omit\",")
    b.append("          \"orig\": \"omit\",")
    b.append("          \"reqd\": false,")
    b.append("          \"type\": \"`\$NUMBER`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/tokenization/tokenize\",")
    b.append("       \"parts\": [")
    b.append("        \"tokenization\",")
    b.append("        \"tokenize\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"omit\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index\$\": 1")
    b.append("      },")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/tokenization/delete\",")
    b.append("       \"parts\": [")
    b.append("        \"tokenization\",")
    b.append("        \"delete\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index\$\": 2")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key\$\": \"create\"")
    b.append("    },")
    b.append("    \"list\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"list\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"query\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"field_name\",")
    b.append("          \"orig\": \"field_name\",")
    b.append("          \"reqd\": false,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"field_value\",")
    b.append("          \"orig\": \"field_value\",")
    b.append("          \"reqd\": false,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"reference\",")
    b.append("          \"orig\": \"reference\",")
    b.append("          \"reqd\": false,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"template_ref\",")
    b.append("          \"orig\": \"template_ref\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/healthcheck/tokenize\",")
    b.append("       \"parts\": [")
    b.append("        \"healthcheck\",")
    b.append("        \"tokenize\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"field_name\",")
    b.append("         \"field_value\",")
    b.append("         \"reference\",")
    b.append("         \"template_ref\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index\$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key\$\": \"list\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"tokenize_batch\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"batch\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`\$ARRAY`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$ARRAY`\",")
    b.append("     \"index\$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"message_id\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"reference\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 2")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"tokenize_batch\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/tokenization/batch/delete\",")
    b.append("       \"parts\": [")
    b.append("        \"tokenization\",")
    b.append("        \"batch\",")
    b.append("        \"delete\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index\$\": 0")
    b.append("      },")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/tokenization/batch/read\",")
    b.append("       \"parts\": [")
    b.append("        \"tokenization\",")
    b.append("        \"batch\",")
    b.append("        \"read\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index\$\": 1")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key\$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"tokenize_read\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"bfid\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`\$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"message_id\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"reference\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"state\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$OBJECT`\",")
    b.append("     \"index\$\": 3")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"value\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$ARRAY`\",")
    b.append("     \"index\$\": 4")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"tokenize_read\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/tokenization/read\",")
    b.append("       \"parts\": [")
    b.append("        \"tokenization\",")
    b.append("        \"read\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index\$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key\$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"validate\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"message_id\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"reference\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"template_ref\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 2")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"validate\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/partner/validate\",")
    b.append("       \"parts\": [")
    b.append("        \"partner\",")
    b.append("        \"validate\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index\$\": 0")
    b.append("      },")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/template/validate\",")
    b.append("       \"parts\": [")
    b.append("        \"template\",")
    b.append("        \"validate\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index\$\": 1")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key\$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  }")
    b.append(" }")
    b.append("}")
    return b.toString()
  }
}
