-- BluefinShieldconex SDK public client (generated by @voxgig/sdkgen).
--
-- SDK constructors (newSdk / testSdk) and one accessor per entity. Entities
-- are generic — every accessor calls the config-driven F.makeEntity, so the
-- operation pipeline is identical for every entity and every API.

module SdkClient
  ( module SdkTypes
  , newSdk
  , newSdk0
  , testSdk
  , testSdk0
  , detokenize
  , tokenize
  , tokenize_batch
  , tokenize_read
  , validate
  ) where

import Data.IORef (readIORef)

import VoxgigStruct (Value (..))
import SdkTypes
import SdkConfig (makeConfig, makeFeature)
import qualified SdkFeatures as F

-- | Construct a live SDK client from an options map (Noval for defaults).
newSdk :: Value -> IO Client
newSdk options = do
  cfg <- makeConfig
  F.makeClientBase cfg makeFeature options

-- | No-argument convenience constructor.
newSdk0 :: IO Client
newSdk0 = newSdk VNoval

-- | Construct a test-mode SDK: testSdk testopts sdkopts.
testSdk :: Value -> Value -> IO Client
testSdk testopts sdkopts = do
  cfg <- makeConfig
  F.sdkTest cfg makeFeature testopts sdkopts

-- | No-argument convenience test constructor.
testSdk0 :: IO Client
testSdk0 = testSdk VNoval VNoval

-- | The active client mode ("live" or "test").
clientMode :: Client -> IO String
clientMode = readIORef . clMode

-- | The Detokenize entity bound to this client.
detokenize :: Client -> Value -> IO Entity
detokenize client entopts = F.makeEntity client "detokenize" entopts

-- | The Tokenize entity bound to this client.
tokenize :: Client -> Value -> IO Entity
tokenize client entopts = F.makeEntity client "tokenize" entopts

-- | The TokenizeBatch entity bound to this client.
tokenize_batch :: Client -> Value -> IO Entity
tokenize_batch client entopts = F.makeEntity client "tokenize_batch" entopts

-- | The TokenizeRead entity bound to this client.
tokenize_read :: Client -> Value -> IO Entity
tokenize_read client entopts = F.makeEntity client "tokenize_read" entopts

-- | The Validate entity bound to this client.
validate :: Client -> Value -> IO Entity
validate client entopts = F.makeEntity client "validate" entopts

