;; BluefinShieldconex SDK public API (generated by @voxgig/sdkgen).
(ns sdk.api
  (:require [sdk.client :as client]
            [sdk.entity.detokenize :as e-detokenize]
            [sdk.entity.tokenize :as e-tokenize]
            [sdk.entity.tokenize_batch :as e-tokenize_batch]
            [sdk.entity.tokenize_read :as e-tokenize_read]
            [sdk.entity.validate :as e-validate]))

(def make-sdk client/make-sdk)
(def test-sdk client/test-sdk)
(def direct client/direct)
(def prepare client/prepare)
(def options-map client/options-map)

;; Detokenize accessor: (detokenize client data)
(defn detokenize [client data] (e-detokenize/make client data))

;; Tokenize accessor: (tokenize client data)
(defn tokenize [client data] (e-tokenize/make client data))

;; TokenizeBatch accessor: (tokenize_batch client data)
(defn tokenize_batch [client data] (e-tokenize_batch/make client data))

;; TokenizeRead accessor: (tokenize_read client data)
(defn tokenize_read [client data] (e-tokenize_read/make client data))

;; Validate accessor: (validate client data)
(defn validate [client data] (e-validate/make client data))
