;; BluefinShieldconex SDK configuration (generated by @voxgig/sdkgen).
(ns sdk.config
  (:require [voxgig.struct :as vs]))

(defn make-config []
  (vs/jm
    "entity" (vs/jm
      "detokenize" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "batch"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$ARRAY`"))
            "req" false
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "bfid"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "message_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "name"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "reference"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "value"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$ARRAY`"))
            "req" false
            "type" "`$ARRAY`"))
        "name" "detokenize"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 0
                "method" "POST"
                "orig" "/tokenization/batch/detokenize"
                "parts" (vs/jt
                  "tokenization"
                  "batch"
                  "detokenize")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 1
                "method" "POST"
                "orig" "/tokenization/detokenize"
                "parts" (vs/jt
                  "tokenization"
                  "detokenize")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "key$" "list"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "bfid"
                      "orig" "bfid"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "field_name"
                      "orig" "field_name"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "field_value"
                      "orig" "field_value"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "reference"
                      "orig" "reference"
                      "reqd" false
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/healthcheck/detokenize"
                "parts" (vs/jt
                  "healthcheck"
                  "detokenize")
                "select" (vs/jm
                  "exist" (vs/jt
                    "bfid"
                    "field_name"
                    "field_value"
                    "reference"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "tokenize" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "batch"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$ARRAY`"))
            "req" false
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "bfid"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "message_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "name"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "reference"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "template_ref"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "value"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$ARRAY`"))
            "req" false
            "type" "`$ARRAY`"))
        "name" "tokenize"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "omit"
                      "orig" "omit"
                      "reqd" false
                      "type" "`$NUMBER`")))
                "index$" 0
                "method" "POST"
                "orig" "/tokenization/batch/tokenize"
                "parts" (vs/jt
                  "tokenization"
                  "batch"
                  "tokenize")
                "select" (vs/jm
                  "exist" (vs/jt
                    "omit"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "omit"
                      "orig" "omit"
                      "reqd" false
                      "type" "`$NUMBER`")))
                "index$" 1
                "method" "POST"
                "orig" "/tokenization/tokenize"
                "parts" (vs/jt
                  "tokenization"
                  "tokenize")
                "select" (vs/jm
                  "exist" (vs/jt
                    "omit"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 2
                "method" "POST"
                "orig" "/tokenization/delete"
                "parts" (vs/jt
                  "tokenization"
                  "delete")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "key$" "list"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "field_name"
                      "orig" "field_name"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "field_value"
                      "orig" "field_value"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "reference"
                      "orig" "reference"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "template_ref"
                      "orig" "template_ref"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/healthcheck/tokenize"
                "parts" (vs/jt
                  "healthcheck"
                  "tokenize")
                "select" (vs/jm
                  "exist" (vs/jt
                    "field_name"
                    "field_value"
                    "reference"
                    "template_ref"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "tokenize_batch" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "batch"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$ARRAY`"))
            "req" false
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "message_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "reference"
            "req" false
            "type" "`$STRING`"))
        "name" "tokenize_batch"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 0
                "method" "POST"
                "orig" "/tokenization/batch/delete"
                "parts" (vs/jt
                  "tokenization"
                  "batch"
                  "delete")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 1
                "method" "POST"
                "orig" "/tokenization/batch/read"
                "parts" (vs/jt
                  "tokenization"
                  "batch"
                  "read")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "tokenize_read" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "bfid"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "message_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "reference"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "state"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "value"
            "req" false
            "type" "`$ARRAY`"))
        "name" "tokenize_read"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 0
                "method" "POST"
                "orig" "/tokenization/read"
                "parts" (vs/jt
                  "tokenization"
                  "read")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "validate" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "message_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "reference"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "template_ref"
            "req" true
            "type" "`$STRING`"))
        "name" "validate"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 0
                "method" "POST"
                "orig" "/partner/validate"
                "parts" (vs/jt
                  "partner"
                  "validate")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 1
                "method" "POST"
                "orig" "/template/validate"
                "parts" (vs/jt
                  "template"
                  "validate")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt))))
    "feature" (vs/jm
      "test" (vs/jm
        "options" (vs/jm
          "active" false)))
    "main" (vs/jm
      "name" "BluefinShieldconex")
    "options" (vs/jm
      "auth" (vs/jm
        "prefix" "Basic")
      "base" "https://secure-cert.shieldconex.com/api"
      "entity" (vs/jm
        "detokenize" (vs/jm)
        "tokenize" (vs/jm)
        "tokenize_batch" (vs/jm)
        "tokenize_read" (vs/jm)
        "validate" (vs/jm))
      "headers" (vs/jm
        "content-type" "application/json"))))
